/**
 * The 2.5D professional: one reference illustration, cut into a base plate
 * and three feather-masked patches that carry the motion.
 *
 * Every patch is the same pixels as the base underneath it, so at rest the
 * stack is indistinguishable from the flat artwork; when a patch moves, the
 * feathered edge blends it back into the unmoved base and the illustration
 * never tears. Generated by `scripts/build-character-layers.py` — the numbers
 * are percentages of the base image, so they survive any display size.
 */

import baseUrl from "./assets/professional-base.webp";
import handUrl from "./assets/professional-hand.webp";
import headUrl from "./assets/professional-head.webp";
import torsoUrl from "./assets/professional-torso.webp";

/** Source size of the base plate. Motion below is expressed in these pixels. */
export const CHARACTER_SOURCE = { width: 803, height: 662, url: baseUrl } as const;

export interface CharacterPatch {
  readonly url: string;
  /** Box, as % of the base plate. */
  readonly left: number;
  readonly top: number;
  readonly width: number;
  readonly height: number;
  /** Pivot the patch rotates around, as % of its own box. */
  readonly originX: number;
  readonly originY: number;
}

/** Shirt and neck: pivots at the hip, breathes and leans. */
export const TORSO_PATCH: CharacterPatch = {
  url: torsoUrl,
  left: 32.628,
  top: 20.091,
  width: 31.009,
  height: 34.29,
  originX: 46.988,
  originY: 96.035,
};

/** Head and hair: pivots at the neck, follows the gaze. */
export const HEAD_PATCH: CharacterPatch = {
  url: headUrl,
  left: 37.733,
  top: 0.906,
  width: 21.669,
  height: 25.831,
  originX: 56.322,
  originY: 88.304,
};

/** The hand on the keys: pivots at the wrist, runs the typing cycle. */
export const HAND_PATCH: CharacterPatch = {
  url: handUrl,
  left: 51.806,
  top: 42.145,
  width: 14.072,
  height: 9.366,
  originX: 29.204,
  originY: 19.355,
};

/**
 * Where the laptop screen faces the character. The light it casts is drawn,
 * not part of the artwork, so it can follow WebChatBot's energy.
 */
export const SCREEN_LIGHT = { x: 52, y: 39 } as const;
